http:  
  port: "8084"
  
hertz:
  host: "system-proxy-hertz-arthi.us-e2.cloudhub.io"
  port: "80" 
  path: "/rentals"  
  

national: 
  host: "national-car-rental-ws.us-e2.cloudhub.io"
  port: "8085"
  basepath: "/"
  protocol: "HTTP"