http:
  port: "8082"
  
hertz:
  host: "0.0.0.0"
  port: "8083"  
  path: "/rentals"  
  

national: 
  host: "national-car-rental-ws.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"