#%RAML 1.0 NamedExample
value:
  -
    ID: 1
    price: 50
    pickupLocation: OHare
    dropoffLocation: Midway
    rentDate: 2020/03/22
    car:
      brand: Nissan Sentra SL
      totalSeats: 5
  
  -
    ID: 2
    price: 100
    pickupLocation: OHare
    dropoffLocation: Midway
    rentDate: 2020/03/22
    car:
      brand: Volvo XC 90
      totalSeats: 7
